backend/config/routes.rb
Rails.application.routes.draw do
  resources :cities
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/app/models/city.rb
class City < ApplicationRecord
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

backend/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: %i[ show edit update destroy ]

  # GET /cities or /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1 or /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities or /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: "City was successfully created." }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: "City was successfully updated." }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: "City was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.require(:city).permit(:population, :region, :government, :importMaterials, :exportMaterials, :armorer, :weaponsSmith, :supplies, :pointOfInterest1, :pointOfInterest2, :pointOfInterest3, :race1, :race2, :race3, :religion1, :religion2, :religion3)
    end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/cities_helper.rb
module CitiesHelper
end

backend/app/views/cities/_form.html.erb
<%= form_with(model: city) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
        <% city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :population %>
    <%= form.number_field :population %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="field">
    <%= form.label :government %>
    <%= form.text_field :government %>
  </div>

  <div class="field">
    <%= form.label :importMaterials %>
    <%= form.text_field :importMaterials %>
  </div>

  <div class="field">
    <%= form.label :exportMaterials %>
    <%= form.text_field :exportMaterials %>
  </div>

  <div class="field">
    <%= form.label :armorer %>
    <%= form.text_field :armorer %>
  </div>

  <div class="field">
    <%= form.label :weaponsSmith %>
    <%= form.text_field :weaponsSmith %>
  </div>

  <div class="field">
    <%= form.label :supplies %>
    <%= form.text_field :supplies %>
  </div>

  <div class="field">
    <%= form.label :pointOfInterest1 %>
    <%= form.text_field :pointOfInterest1 %>
  </div>

  <div class="field">
    <%= form.label :pointOfInterest2 %>
    <%= form.text_field :pointOfInterest2 %>
  </div>

  <div class="field">
    <%= form.label :pointOfInterest3 %>
    <%= form.text_field :pointOfInterest3 %>
  </div>

  <div class="field">
    <%= form.label :race1 %>
    <%= form.text_field :race1 %>
  </div>

  <div class="field">
    <%= form.label :race2 %>
    <%= form.text_field :race2 %>
  </div>

  <div class="field">
    <%= form.label :race3 %>
    <%= form.text_field :race3 %>
  </div>

  <div class="field">
    <%= form.label :religion1 %>
    <%= form.text_field :religion1 %>
  </div>

  <div class="field">
    <%= form.label :religion2 %>
    <%= form.text_field :religion2 %>
  </div>

  <div class="field">
    <%= form.label :religion3 %>
    <%= form.text_field :religion3 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

backend/app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th>Population</th>
      <th>Region</th>
      <th>Government</th>
      <th>Importmaterials</th>
      <th>Exportmaterials</th>
      <th>Armorer</th>
      <th>Weaponssmith</th>
      <th>Supplies</th>
      <th>Pointofinterest1</th>
      <th>Pointofinterest2</th>
      <th>Pointofinterest3</th>
      <th>Race1</th>
      <th>Race2</th>
      <th>Race3</th>
      <th>Religion1</th>
      <th>Religion2</th>
      <th>Religion3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.population %></td>
        <td><%= city.region %></td>
        <td><%= city.government %></td>
        <td><%= city.importMaterials %></td>
        <td><%= city.exportMaterials %></td>
        <td><%= city.armorer %></td>
        <td><%= city.weaponsSmith %></td>
        <td><%= city.supplies %></td>
        <td><%= city.pointOfInterest1 %></td>
        <td><%= city.pointOfInterest2 %></td>
        <td><%= city.pointOfInterest3 %></td>
        <td><%= city.race1 %></td>
        <td><%= city.race2 %></td>
        <td><%= city.race3 %></td>
        <td><%= city.religion1 %></td>
        <td><%= city.religion2 %></td>
        <td><%= city.religion3 %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

backend/app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

backend/app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Population:</strong>
  <%= @city.population %>
</p>

<p>
  <strong>Region:</strong>
  <%= @city.region %>
</p>

<p>
  <strong>Government:</strong>
  <%= @city.government %>
</p>

<p>
  <strong>Importmaterials:</strong>
  <%= @city.importMaterials %>
</p>

<p>
  <strong>Exportmaterials:</strong>
  <%= @city.exportMaterials %>
</p>

<p>
  <strong>Armorer:</strong>
  <%= @city.armorer %>
</p>

<p>
  <strong>Weaponssmith:</strong>
  <%= @city.weaponsSmith %>
</p>

<p>
  <strong>Supplies:</strong>
  <%= @city.supplies %>
</p>

<p>
  <strong>Pointofinterest1:</strong>
  <%= @city.pointOfInterest1 %>
</p>

<p>
  <strong>Pointofinterest2:</strong>
  <%= @city.pointOfInterest2 %>
</p>

<p>
  <strong>Pointofinterest3:</strong>
  <%= @city.pointOfInterest3 %>
</p>

<p>
  <strong>Race1:</strong>
  <%= @city.race1 %>
</p>

<p>
  <strong>Race2:</strong>
  <%= @city.race2 %>
</p>

<p>
  <strong>Race3:</strong>
  <%= @city.race3 %>
</p>

<p>
  <strong>Religion1:</strong>
  <%= @city.religion1 %>
</p>

<p>
  <strong>Religion2:</strong>
  <%= @city.religion2 %>
</p>

<p>
  <strong>Religion3:</strong>
  <%= @city.religion3 %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RpgCityMaker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>